name: multiple_screens
description:
  Flutter plugin for determing whether the device supports multiple screens and
  whether the app is currently spanned across both screen.
version: 0.3.0
homepage: https://github.com/builttoroam/multiple_screens

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.builttoroam.multiple_screens
        pluginClass: MultipleScreensPlugin
